apiVersion: v1
kind: Service
metadata:
  name: employee-management-api-service
  namespace: default
  labels:
    app: employee-management-api
spec:
  type: LoadBalancer
  selector:
    app: employee-management-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
